### ISSUE TITLE
Already initialized constant Exception

### ISSUE THREAD

**Issue by josepjaume** [mirah/pindah#26] opened 2012-01-30 10:34 UTC
Hi!

I'm using pindah master (since it has an updated build.xml that's needed in latest android sdk) and when I try "rake compile" it throws an exception `already initialized constant Exception`.

That's the exact output I get:

```
-setup:
Gathering info for standapp...
Android SDK Tools Revision 16
Project Target: Android 2.1
API level: 7

------------------
Resolving library dependencies:
No library dependencies.

------------------

WARNING: No minSdkVersion value set. Application will install on all Android versions.

-build-setup:
Creating output directories if needed...

-pre-build:

-code-gen:
----------
Handling aidl files...
No AIDL files to compile.
----------
Handling RenderScript files...
No RenderScript files to compile.
----------
Handling Resources...
No changed resources. R.java and Manifest.java untouched.

-pre-compile:

javac:

-compile:
compiling Mirah source in /Users/josepjaume/Projects/standapp/src/. to /Users/josepjaume/Projects/standapp/bin/classes
/Users/josepjaume/.rvm/rubies/jruby-1.6.5/lib/ruby/site_ruby/shared/builtin/javasupport/core_ext/object.rb:99 warning: already initialized constant Exception
Parsing...
rake aborted!
org.apache.tools.ant.BuildException: org.jruby.exceptions.RaiseException: (RuntimeError) nothing to parse? [".", "./com", "./com/codegram", "./com/codegram/standapp"]

Tasks: TOP => compile
(See full trace by running task with --trace)
```

Note that I'm using a `Gemfile` with the following contents:

```
source :rubygems

gem 'pindah', :git => 'git://github.com/mirah/pindah.git'
gem 'rake', '>= 0.9'
```

And I had to add the following line to the Rakefile to complain with Rake::DSL:

```
require 'rake/dsl_definition'
```

Any light on this? Thanks, this project is absolutely amazing.

**Comment by abscondment** [comment] 2012-01-30 16:12
That warning actually appears all the time - it's definitely misleading,
but it's not the cause of your error.

The real exception is this:

org.apache.tools.ant.BuildException: org.jruby.exceptions.RaiseException:
(RuntimeError) nothing to parse? [".", "./com", "./com/codegram",
"./com/codegram/standapp"]

Are there any source files is those paths?

**Comment by abscondment** [comment] 2013-02-15 21:38
@josepjaume, I'm going to close this since a lot has changed in a year. Please reopen it if you hit the same issues in master (or 0.1.3 once it's out there).

**Closed as completed by abscondment** 2013-02-15 21:38 UTC
