### ISSUE TITLE
Compilation problems with android-tools R20 and pindah-git

### ISSUE THREAD

**Issue by thypon** [mirah/pindah#31] opened 2012-11-19 10:03 UTC
The error is the same of that

http://stackoverflow.com/questions/11255805/use-ant-clean-test-with-the-newest-android-sdk-renderscript-opt-level-is

```
-check-env:
Android SDK Tools Revision 21
Installed at /home/gattuso/DevTools/android-sdk-linux

-setup:
Project Name: hello_world
Project Type: Application

-build-setup:
Resolving Build Target for hello_world...
Project Target:   Android 2.3.3
API level:        10
WARNING: No minSdkVersion value set. Application will install on all Android versions.
----------
Creating output directories if needed...
----------
Resolving Dependencies for hello_world...
Library dependencies:
No Libraries

------------------
API<=15: Adding annotations.jar to the classpath.
----------
Building Libraries with '${build.target}'...
No sub-builds to iterate on

-pre-build:

-code-gen:
No changes in the AndroidManifest files.
Handling aidl files...
No AIDL files to compile.
----------
Handling RenderScript files...
/home/gattuso/.rvm/gems/jruby-1.7.0@global/gems/rake-0.9.2.2/lib/rake/task.rb:168 warning: singleton on non-persistent Java type Java::OrgApacheToolsAnt::BuildException (http://wiki.jruby.org/Persistence)
rake aborted!
The following error occurred while executing this line:
/home/gattuso/DevTools/android-sdk-linux/tools/ant/build.xml:665: '${renderscript.opt.level}' is not a permitted value for com.android.ant.RenderScriptTask$OptLevel

Tasks: TOP => compile
(See full trace by running task with --trace)
```

**Comment by abscondment** [comment] 2013-02-14 01:35
That link (and the [page it points to](https://issues.apache.org/jira/browse/CB-974)) indicates the problem isn't with Pindah; it's an android tools issue. They say adding `renderscript.opt.level=O0` fixes things; I'm closing this out since it's not our bug afaict.

As an aside, I don't repro with Android SDK Tools Revision 21.0.1 -- maybe they fixed it.

**Closed as completed by abscondment** 2013-02-14 01:35 UTC

**Comment by apaleslimghost** [comment] 2014-01-02 13:24
> adding `renderscript.opt.level=O0`

Where exactly? I've put it in an ant.properties at the project root, but it doesn't seem to be loaded. This is happening with Android Tools R22.3.

**Edit** scratch that, putting it in local.properties works.
